server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-dalhsdn40ujc73e3gkug-a:5432/ingresse_ai}
spring.datasource.username=${DB_USERNAME:ingresse_ai_user}
spring.datasource.password=${DB_PASSWORD:hFEH2TEbomEX9nWoi4KGQMEq42sZ538H}

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

springdoc.swagger-ui.path=/docs
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
chat.ai.api-key=${GEMINI_API_KEY:}
chat.ai.model=${GEMINI_MODEL:gemini-2.0-flash}
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false